//
//  RSDeploymentAvailability.h
//  RSCoreFoundation
//
//  Created by RetVal on 12/27/12.
//  Copyright (c) 2012 RetVal. All rights reserved.
//

#ifndef RSCoreFoundation_RSDeploymentAvailability_h
#define RSCoreFoundation_RSDeploymentAvailability_h

#ifndef DEPLOYMENT_TARGET_MACOSX 
#define DEPLOYMENT_TARGET_MACOSX 1
#endif

#if defined(__GNUC__) && ((__GNUC__ >= 4) || ((__GNUC__ == 3) && (__GNUC_MINOR__ >= 1)))
    #define RS_DEPRECATED_ATTRIBUTE __attribute__((deprecated))
    #if defined(__clang__) && __has_extension(attribute_deprecated_with_message)
        #define RS_DEPRECATED_ATTRIBUTE_REASON(R) __attribute__((deprecated(R)))
    #else
        #define RS_DEPRECATED_ATTRIBUTE_REASON(R) RS_DEPRECATED_ATTRIBUTE
    #endif
#else
    #define RS_DEPRECATED_ATTRIBUTE
    #define RS_DEPRECATED_ATTRIBUTE_REASON(R) RS_DEPRECATED_ATTRIBUTE
#endif

#if defined(__GNUC__) && ((__GNUC__ >= 4) || ((__GNUC__ == 3) && (__GNUC_MINOR__ >= 1)))
    #define RS_UNAVAILABLE_ATTRIBUTE __attribute__((unavailable))
    #if defined(__clang__) && __has_extension(attribute_unavailable_with_message)
        #define RS_UNAVAILABLE_ATTRIBUTE_REASON(R) __attribute__((unavailable(R)))
    #else
        #define RS_UNAVAILABLE_ATTRIBUTE_REASON(R) RS_UNAVAILABLE_ATTRIBUTE
    #endif
#else
    #define RS_UNAVAILABLE_ATTRIBUTE
    #define RS_UNAVAILABLE_ATTRIBUTE_REASON(R) RS_UNAVAILABLE_ATTRIBUTE
#endif

#define RSCoreFoundationVersionNumber0_0         744
#define RSCoreFoundationVersionNumber0_1         812
#define RSCoreFoundationVersionNumber0_2        1000
#define RSCoreFoundationVersionNumber0_3        1200
#define RSCoreFoundationVersionNumber0_4        1400
#define RSCoreFoundationVersionNumber0_5        2000

#ifndef RSCoreFoundationVersionNumberCurrent
#define RSCoreFoundationVersionNumberCurrent   RSCoreFoundationVersionNumber0_4
#endif

/*
 available - 0.0
 deprecated - 0.0
 available 0.0 but deprecated 0.1
 */

#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_0  RS_DEPRECATED_ATTRIBUTE

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_0
#define AVAILABLE_RSCF_VERSION_0_0_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_0      RS_DEPRECATED_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_0    RS_UNAVAILABLE_ATTRIBUTE
#else
#define AVAILABLE_RSCF_VERSION_0_0_AND_LATER   RS_UNAVAILABLE_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_0      RS_UNAVAILABLE_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_0    
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_1
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_1  RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_1  RS_DEPRECATED_ATTRIBUTE
#else
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_1  
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_1  AVAILABLE_RSCF_VERSION_0_1_AND_LATER
#endif

/*
 available - 0.1
 deprecated - 0.1
 // available 0.1 but deprecated 0.2
 */
#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_1
#define AVAILABLE_RSCF_VERSION_0_1_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_1      RS_DEPRECATED_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_1    RS_UNAVAILABLE_ATTRIBUTE
#else
#define AVAILABLE_RSCF_VERSION_0_1_AND_LATER   RS_UNAVAILABLE_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_1      RS_UNAVAILABLE_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_1
#endif


#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_2
#define AVAILABLE_RSCF_VERSION_0_2_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_2      RS_DEPRECATED_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_2    RS_UNAVAILABLE_ATTRIBUTE
#else
#define AVAILABLE_RSCF_VERSION_0_2_AND_LATER   RS_UNAVAILABLE_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_2      RS_UNAVAILABLE_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_2
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_2
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_2 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_2 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_2 RS_DEPRECATED_ATTRIBUTE
#else
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_2 AVAILABLE_RSCF_VERSION_0_0_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_2 AVAILABLE_RSCF_VERSION_0_1_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_2 AVAILABLE_RSCF_VERSION_0_2_AND_LATER
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_3
#define AVAILABLE_RSCF_VERSION_0_3_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_3      RS_DEPRECATED_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_3    RS_UNAVAILABLE_ATTRIBUTE
#else
#define AVAILABLE_RSCF_VERSION_0_3_AND_LATER   RS_UNAVAILABLE_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_3      RS_UNAVAILABLE_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_3
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_3
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_3 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_3 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_3 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_3 RS_DEPRECATED_ATTRIBUTE
#else
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_3 AVAILABLE_RSCF_VERSION_0_0_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_3 AVAILABLE_RSCF_VERSION_0_1_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_3 AVAILABLE_RSCF_VERSION_0_2_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_3 AVAILABLE_RSCF_VERSION_0_3_AND_LATER
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_4
#define AVAILABLE_RSCF_VERSION_0_4_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_4      RS_DEPRECATED_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_4    RS_UNAVAILABLE_ATTRIBUTE
#else
#define AVAILABLE_RSCF_VERSION_0_4_AND_LATER   RS_UNAVAILABLE_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_4      RS_UNAVAILABLE_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_4
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_4
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_4 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_4 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_4 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_4 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_4_DEP_0_4 RS_DEPRECATED_ATTRIBUTE
#else
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_4 AVAILABLE_RSCF_VERSION_0_0_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_4 AVAILABLE_RSCF_VERSION_0_1_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_4 AVAILABLE_RSCF_VERSION_0_2_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_4 AVAILABLE_RSCF_VERSION_0_3_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_4_DEP_0_4 AVAILABLE_RSCF_VERSION_0_4_AND_LATER
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_5
#define AVAILABLE_RSCF_VERSION_0_5_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_5      RS_DEPRECATED_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_5    RS_UNAVAILABLE_ATTRIBUTE
#else
#define AVAILABLE_RSCF_VERSION_0_5_AND_LATER   RS_UNAVAILABLE_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_5      RS_UNAVAILABLE_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_5
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_5
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_5 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_5 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_5 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_5 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_4_DEP_0_5 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_5_DEP_0_5 RS_DEPRECATED_ATTRIBUTE
#else
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_5 AVAILABLE_RSCF_VERSION_0_0_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_5 AVAILABLE_RSCF_VERSION_0_1_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_5 AVAILABLE_RSCF_VERSION_0_2_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_5 AVAILABLE_RSCF_VERSION_0_3_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_4_DEP_0_5 AVAILABLE_RSCF_VERSION_0_4_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_5_DEP_0_5 AVAILABLE_RSCF_VERSION_0_5_AND_LATER
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_5
#define AVAILABLE_RSCF_VERSION_0_5_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_5      RS_DEPRECATED_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_5    RS_UNAVAILABLE_ATTRIBUTE
#else
#define AVAILABLE_RSCF_VERSION_0_5_AND_LATER   RS_UNAVAILABLE_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_5      RS_UNAVAILABLE_ATTRIBUTE
#define __UNAVAILABILITY_INTERNAL__RSCF_0_5
#endif

#if RSCoreFoundationVersionNumberCurrent >= RSCoreFoundationVersionNumber0_6
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_6 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_6 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_6 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_6 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_4_DEP_0_6 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_5_DEP_0_6 RS_DEPRECATED_ATTRIBUTE
#define __AVAILABILITY_INTERNAL__RSCF_0_6_DEP_0_6 RS_DEPRECATED_ATTRIBUTE
#else
#define __AVAILABILITY_INTERNAL__RSCF_0_0_DEP_0_6 AVAILABLE_RSCF_VERSION_0_0_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_1_DEP_0_6 AVAILABLE_RSCF_VERSION_0_1_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_2_DEP_0_6 AVAILABLE_RSCF_VERSION_0_2_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_3_DEP_0_6 AVAILABLE_RSCF_VERSION_0_3_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_4_DEP_0_6 AVAILABLE_RSCF_VERSION_0_4_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_5_DEP_0_6 AVAILABLE_RSCF_VERSION_0_5_AND_LATER
#define __AVAILABILITY_INTERNAL__RSCF_0_6_DEP_0_6 AVAILABLE_RSCF_VERSION_0_6_AND_LATER
#endif



#ifndef __RS_AVAILABLE_STARTING
#define __RS_AVAILABLE_STARTING(_str)    __AVAILABILITY_INTERNAL__RSCF##_str
#define __RS_UNAVAILABLE_STARTING(_str)    __UNAVAILABILITY_INTERNAL__RSCF##_str
#define __RS_AVAILABLE_BUT_DEPRECATED(_rsIntro, _rsDep) __AVAILABILITY_INTERNAL__RSCF_##_rsIntro##_DEP_##_rsDep
#endif

#endif
